export { default as HomePage} from './Home/Home'
export { default as ItemDetailPage } from './ItemDetail/ItemDetail'
export { default as ContactoPage } from './Contacto/Contacto'
export { default as AyudaPage } from './Ayuda/Ayuda'
export { default as NovedadesPage } from './Novedades/Novedades'